export const UPDATE_PAGE_CONTENT_STATE = 'UPDATE_PAGE_CONTENT_STATE';

export const UPDATE_AUTH = 'UPDATE_AUTH';

export const UPDATE_LOGIN_POPUP_STATE = 'UPDATE_LOGIN_POPUP_STATE';
export const UPDATE_SIGNUP_POPUP_STATE = 'UPDATE_SIGNUP_POPUP_STATE';

export const UPDATE_NOTIFICATION_STATE = 'UPDATE_NOTIFICATION_STATE';