export const UPDATE_LOADER_STATE = 'UPDATE_LOADER_STATE';

export const UPDATE_PAGE_CONTENT_STATE = 'UPDATE_PAGE_CONTENT_STATE';

export const UPDATE_AUTH = 'UPDATE_AUTH';

export const UPDATE_POPUP_STATE = 'UPDATE_POPUP_STATE';

export const UPDATE_NOTIFICATION_STATE = 'UPDATE_NOTIFICATION_STATE';

export const UPDATE_RELEASES = 'UPDATE_RELEASES';

export const UPDATE_USERS = 'UPDATE_USERS';